#!/usr/bin/env sh
set -eu

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
WEB_DIR="$ROOT_DIR/web"
NON_INTERACTIVE=false
FORCE=false
MODE=""
for arg in "$@"; do
  case "$arg" in
    --non-interactive) NON_INTERACTIVE=true ;;
    --native) MODE=native ;;
    --docker) MODE=docker ;;
    --force) FORCE=true ;;
    -h|--help) printf '%s\n' "Usage: ./install.sh [--docker|--native] [--non-interactive] [--force]"; exit 0 ;;
    *) printf '%s\n' "Unknown option: $arg" >&2; exit 1 ;;
  esac
done
[ -f "$WEB_DIR/package.json" ] && [ -f "$WEB_DIR/compose.yaml" ] || { printf '%s\n' "Run this script from a complete TimeTone checkout." >&2; exit 1; }

ask() {
  prompt=$1 default=$2
  if [ "$NON_INTERACTIVE" = true ]; then printf '%s' "$default"; return; fi
  printf '%s [%s]: ' "$prompt" "$default" >&2
  IFS= read -r answer || true
  printf '%s' "${answer:-$default}"
}

[ -n "$MODE" ] || MODE=${TIMETONE_MODE:-}
if [ -z "$MODE" ]; then
  if [ "$NON_INTERACTIVE" = true ]; then MODE=docker
  else
    DEFAULT_MODE=docker
    command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1 || DEFAULT_MODE=native
    MODE=$(ask "Install mode (docker/native)" "$DEFAULT_MODE")
  fi
fi
case "$MODE" in docker|native) ;; *) printf '%s\n' "Choose docker or native as the install mode." >&2; exit 1 ;; esac

if [ "$MODE" = docker ]; then
  command -v docker >/dev/null 2>&1 || { printf '%s\n' "Docker is not installed. Choose --native or install Docker Engine first." >&2; exit 1; }
  docker compose version >/dev/null 2>&1 || { printf '%s\n' "Docker Compose v2 is required (docker compose)." >&2; exit 1; }
else
  command -v node >/dev/null 2>&1 || { printf '%s\n' "Node.js 20.9 or newer is required for a native install." >&2; exit 1; }
  command -v npm >/dev/null 2>&1 || { printf '%s\n' "npm is required for a native install." >&2; exit 1; }
fi

if [ -f "$WEB_DIR/.env" ] && [ "$FORCE" = false ] && [ "$NON_INTERACTIVE" = false ]; then
  printf 'An existing web/.env was found. Replace it? [y/N]: ' >&2
  IFS= read -r replace || true
  case "$replace" in y|Y|yes|YES) ;; *)
    printf '%s\n' "Kept existing configuration. Starting TimeTone…"
    if [ "$MODE" = docker ]; then (cd "$WEB_DIR" && docker compose up -d --build)
    else (cd "$WEB_DIR" && npm run build >/dev/null && PORT="$PORT" nohup npm run start -- --hostname 0.0.0.0 > timetone.log 2>&1 &)
    fi
    exit 0 ;;
  esac
fi

ADMIN_PASSWORD=${TIMETONE_ADMIN_PASSWORD:-}
if [ -z "$ADMIN_PASSWORD" ]; then
  [ "$NON_INTERACTIVE" = false ] || { printf '%s\n' "TIMETONE_ADMIN_PASSWORD is required with --non-interactive." >&2; exit 1; }
  while [ ${#ADMIN_PASSWORD} -lt 8 ]; do
    printf 'Create an admin password (at least 8 characters): ' >&2
    stty -echo; IFS= read -r ADMIN_PASSWORD || true; stty echo; printf '\n' >&2
    [ ${#ADMIN_PASSWORD} -ge 8 ] || printf '%s\n' "Please use at least 8 characters." >&2
  done
fi
PORT=${TIMETONE_PORT:-$(ask "LAN port" "3000")}
TIMEZONE=${TIMEKEEP_TIMEZONE:-$(ask "Office timezone (IANA name)" "Europe/Amsterdam")}
case "$PORT" in *[!0-9]*|'') printf '%s\n' "TIMETONE_PORT must be a number." >&2; exit 1;; esac
if command -v openssl >/dev/null 2>&1; then SECRET=$(openssl rand -hex 32); else SECRET=$(date +%s | sha256sum | awk '{print $1}'); fi
umask 077
if [ "$MODE" = native ]; then mkdir -p "$WEB_DIR/data"; DATABASE_LINE="DATABASE_PATH=$WEB_DIR/data/timekeep.db"; else DATABASE_LINE=""; fi
cat > "$WEB_DIR/.env" <<EOF
# Generated by TimeTone install.sh — keep this file private.
ADMIN_PASSWORD=$ADMIN_PASSWORD
ADMIN_SECRET=$SECRET
COOKIE_SECURE=false
TIMEKEEP_TIMEZONE=$TIMEZONE
TIMETONE_PORT=$PORT
$DATABASE_LINE
EOF

printf '%s\n' "Installing TimeTone ($MODE)…"
if [ "$MODE" = docker ]; then
  (cd "$WEB_DIR" && docker compose config -q && docker compose up -d --build)
else
  (cd "$WEB_DIR" && npm install && npm run build)
  if [ -f "$WEB_DIR/timetone.pid" ] && kill -0 "$(cat "$WEB_DIR/timetone.pid")" 2>/dev/null; then kill "$(cat "$WEB_DIR/timetone.pid")" 2>/dev/null || true; fi
  (cd "$WEB_DIR" && PORT="$PORT" nohup npm run start -- --hostname 0.0.0.0 > timetone.log 2>&1 & echo $! > timetone.pid)
fi
HOST_IP=$(hostname -I 2>/dev/null | awk '{print $1}')
printf '\nTimeTone is ready at http://%s:%s\n' "${HOST_IP:-localhost}" "$PORT"
[ "$MODE" = native ] && printf '%s\n' "Native logs: $WEB_DIR/timetone.log  |  PID file: $WEB_DIR/timetone.pid"
printf '%s\n' "For browser-based USB updates, serve this address through HTTPS (or use localhost)."
