#!/usr/bin/env sh
# TimeTone's interactive self-hosted installer. Run from a release checkout.
set -eu

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
WEB_DIR="$ROOT_DIR/web"
NON_INTERACTIVE=false
FORCE=false
for arg in "$@"; do
  case "$arg" in
    --non-interactive) NON_INTERACTIVE=true ;;
    --force) FORCE=true ;;
    -h|--help)
      printf '%s\n' "Usage: ./install.sh [--non-interactive] [--force]"
      printf '%s\n' "Set TIMETONE_ADMIN_PASSWORD, TIMETONE_PORT and TIMEKEEP_TIMEZONE for non-interactive use."
      exit 0 ;;
    *) printf '%s\n' "Unknown option: $arg" >&2; exit 1 ;;
  esac
done

command -v docker >/dev/null 2>&1 || { printf '%s\n' "Docker is required. Install Docker Engine and the Compose plugin, then rerun this script." >&2; exit 1; }
docker compose version >/dev/null 2>&1 || { printf '%s\n' "Docker Compose v2 is required (docker compose)." >&2; exit 1; }
[ -f "$WEB_DIR/compose.yaml" ] || { printf '%s\n' "Run this script from a complete TimeTone checkout." >&2; exit 1; }

ask() {
  prompt=$1 default=$2
  if [ "$NON_INTERACTIVE" = true ]; then printf '%s' "$default"; return; fi
  printf '%s [%s]: ' "$prompt" "$default" >&2
  IFS= read -r answer || true
  printf '%s' "${answer:-$default}"
}

if [ -f "$WEB_DIR/.env" ] && [ "$FORCE" = false ] && [ "$NON_INTERACTIVE" = false ]; then
  printf 'An existing web/.env was found. Replace it? [y/N]: ' >&2
  IFS= read -r replace || true
  case "$replace" in y|Y|yes|YES) ;; *) printf '%s\n' "Kept existing configuration. Starting TimeTone…"; (cd "$WEB_DIR" && docker compose up -d --build); exit 0 ;; esac
fi

ADMIN_PASSWORD=${TIMETONE_ADMIN_PASSWORD:-}
if [ -z "$ADMIN_PASSWORD" ]; then
  [ "$NON_INTERACTIVE" = false ] || { printf '%s\n' "TIMETONE_ADMIN_PASSWORD is required with --non-interactive." >&2; exit 1; }
  while [ ${#ADMIN_PASSWORD} -lt 8 ]; do
    printf 'Create an admin password (at least 8 characters): ' >&2
    stty -echo; IFS= read -r ADMIN_PASSWORD || true; stty echo; printf '\n' >&2
    [ ${#ADMIN_PASSWORD} -ge 8 ] || printf '%s\n' "Please use at least 8 characters." >&2
  done
fi
PORT=${TIMETONE_PORT:-$(ask "LAN port" "3000")}
TIMEZONE=${TIMEKEEP_TIMEZONE:-$(ask "Office timezone (IANA name)" "Europe/Amsterdam")}
case "$PORT" in *[!0-9]*|'') printf '%s\n' "TIMETONE_PORT must be a number." >&2; exit 1;; esac

if command -v openssl >/dev/null 2>&1; then SECRET=$(openssl rand -hex 32); else SECRET=$(date +%s | sha256sum | awk '{print $1}'); fi
umask 077
cat > "$WEB_DIR/.env" <<EOF
# Generated by TimeTone install.sh — keep this file private.
ADMIN_PASSWORD=$ADMIN_PASSWORD
ADMIN_SECRET=$SECRET
COOKIE_SECURE=false
TIMEKEEP_TIMEZONE=$TIMEZONE
TIMETONE_PORT=$PORT
EOF

printf '%s\n' "Starting TimeTone…"
(cd "$WEB_DIR" && docker compose config -q && docker compose up -d --build)
HOST_IP=$(hostname -I 2>/dev/null | awk '{print $1}')
printf '\nTimeTone is ready at http://%s:%s\n' "${HOST_IP:-localhost}" "$PORT"
printf '%s\n' "For browser-based USB updates, serve this address through HTTPS (or use localhost)."
