"use client";

import { useState } from "react";
import { Download, RefreshCw, Rocket } from "lucide-react";

type Release = { current: string; latest?: string; name?: string; url?: string; notes?: string; updateAvailable?: boolean; error?: string };
export function ReleaseUpdater() {
  const [release, setRelease] = useState<Release | null>(null);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  async function check() { setBusy(true); setMessage(""); try { const response = await fetch("/api/update/check", { cache: "no-store" }); const data = await response.json() as Release; setRelease(data); if (!response.ok) setMessage(data.error || "Update check failed."); } catch { setMessage("Unable to reach GitHub."); } finally { setBusy(false); } }
  async function install() { if (!release?.latest) return; setBusy(true); setMessage(""); try { const response = await fetch("/api/update/install", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ tag: release.latest }) }); const data = await response.json() as { message?: string; error?: string }; setMessage(response.ok ? data.message || "Update started." : data.error || "Update failed."); } catch { setMessage("Update request failed."); } finally { setBusy(false); } }
  return <div className="rounded-xl border border-black/8 bg-[#f5f6f2] p-4 dark:border-white/10 dark:bg-[#243127]"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium">Software updates</p><p className="mt-1 text-sm leading-5 text-black/50 dark:text-white/60">Check GitHub for the newest stable TimeTone release.</p>{release?.latest && <p className="mt-2 text-xs text-black/55 dark:text-white/65">Installed {release.current} · Latest {release.latest}</p>}</div><div className="flex gap-2"><button type="button" onClick={check} disabled={busy} className="inline-flex h-9 items-center gap-2 rounded-lg border border-black/12 bg-white px-3 text-sm font-medium transition hover:-translate-y-0.5 disabled:opacity-50 dark:border-white/15 dark:bg-[#1b261f]"><RefreshCw className={`size-4 ${busy ? "animate-spin" : ""}`} />Check for updates</button>{release?.updateAvailable && <button type="button" onClick={install} disabled={busy} className="inline-flex h-9 items-center gap-2 rounded-lg bg-[#17211b] px-3 text-sm font-medium text-white transition hover:-translate-y-0.5 disabled:opacity-50"><Rocket className="size-4" />Install {release.latest}</button>}</div></div>{release?.updateAvailable && <p className="mt-3 rounded-lg bg-[#eaf4d5] px-3 py-2 text-sm text-[#40552c] dark:bg-[#33472f] dark:text-[#d8ff62]">A new stable release is ready. Your current settings and database are kept during the update.</p>}{release && !release.updateAvailable && !release.error && <p className="mt-3 text-sm text-emerald-700 dark:text-emerald-300">You are up to date.</p>}{message && <p className="mt-3 text-sm text-black/60 dark:text-white/70">{message}</p>}{release?.url && <a className="mt-3 inline-flex items-center gap-1 text-xs font-medium text-black/55 hover:text-black dark:text-white/60 dark:hover:text-white" href={release.url} target="_blank" rel="noreferrer"><Download className="size-3.5" />View release notes on GitHub</a>}</div>;
}
